steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/show-project", "--build-arg=JAR_FILE=target/show-project-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/show-project"]
